# Generated by Django 2.0.4 on 2018-05-01 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_iteminstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iteminstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set item as returned'),)},
        ),
    ]
